const state={panel:'assets',lang:'en',zoom:.8,selected:null,history:[],redo:[]};
const artboard=document.getElementById('artboard');
const panelContent=document.getElementById('panelContent');
const viewport=document.getElementById('canvasViewport');
const shell=document.getElementById('artboardShell');

const assets=[
{name:'Neuron',cat:'Neuroscience',svg:`<svg viewBox="0 0 90 70"><g fill="none" stroke="#3d8b86" stroke-width="4" stroke-linecap="round"><path d="M34 36C20 22 15 11 6 5"/><path d="M34 36C18 40 11 52 4 63"/><path d="M34 36C18 34 10 34 3 34"/><path d="M53 36C67 35 75 29 87 18"/><path d="M53 36C68 40 76 49 88 60"/></g><ellipse cx="43" cy="36" rx="16" ry="14" fill="#dff2ef" stroke="#3d8b86" stroke-width="3"/><circle cx="43" cy="36" r="5" fill="#78bcb6"/></svg>`},
{name:'Mitochondrion',cat:'Cell biology',svg:`<svg viewBox="0 0 90 60"><path d="M8 30C9 9 27 6 43 11c13 4 22-4 34 2 14 7 13 34-3 40-12 5-21-3-34 0-18 5-33-3-32-23Z" fill="#fee8cf" stroke="#d48d4c" stroke-width="3"/><path d="M22 21c9 11 14-8 23 5s14-6 25 5" fill="none" stroke="#d48d4c" stroke-width="3"/></svg>`},
{name:'DNA',cat:'Molecular biology',svg:`<svg viewBox="0 0 80 70"><path d="M20 5c28 18 12 43 40 60M60 5C32 23 48 48 20 65" fill="none" stroke="#6c5aa8" stroke-width="4"/><g stroke="#9d91cb" stroke-width="2"><path d="M27 12h26"/><path d="M22 24h36"/><path d="M27 36h26"/><path d="M22 48h36"/><path d="M27 60h26"/></g></svg>`},
{name:'Cell',cat:'Cell biology',svg:`<svg viewBox="0 0 80 70"><path d="M11 37C8 18 21 7 41 8s31 12 29 30c-2 17-14 25-31 24S14 54 11 37Z" fill="#e8f5ee" stroke="#5d9f80" stroke-width="3"/><circle cx="42" cy="35" r="12" fill="#b9decf" stroke="#5d9f80" stroke-width="2"/><circle cx="28" cy="23" r="3" fill="#f1ba75"/><circle cx="58" cy="49" r="3" fill="#f1ba75"/></svg>`},
{name:'Protein',cat:'Biochemistry',svg:`<svg viewBox="0 0 80 70"><path d="M12 44c5-27 29-39 47-24 17 14 7 38-11 39-17 1-19-19-36-15Z" fill="#e6eef8" stroke="#4f7da2" stroke-width="3"/><path d="M24 38c7-13 20-15 31-7-2 12-12 18-25 15" fill="none" stroke="#7fa3c1" stroke-width="3"/></svg>`},
{name:'Mouse',cat:'Models',svg:`<svg viewBox="0 0 90 70"><ellipse cx="43" cy="39" rx="27" ry="18" fill="#eef0f2" stroke="#7b8992" stroke-width="3"/><circle cx="66" cy="33" r="10" fill="#eef0f2" stroke="#7b8992" stroke-width="3"/><circle cx="69" cy="23" r="5" fill="#f2cfd1" stroke="#7b8992" stroke-width="2"/><circle cx="72" cy="32" r="2" fill="#273847"/><path d="M17 44C2 45 4 60 17 58" fill="none" stroke="#7b8992" stroke-width="3"/></svg>`}
];

function assetPanel(){return `<h2 class="panel-title" data-en="Scientific library" data-fa="کتابخانه علمی">Scientific library</h2><div class="search-box"><input id="assetSearch" placeholder="Search cells, proteins, organs…"></div><div class="chip-row"><button class="chip active">All</button><button class="chip">Cell</button><button class="chip">Neuro</button><button class="chip">Molecular</button></div><div class="section-label"><span>Recommended</span><span style="color:var(--muted);font-weight:500">${assets.length} assets</span></div><div id="assetGrid" class="asset-grid">${assets.map((a,i)=>`<button class="asset-card" data-asset="${i}">${a.svg}<small>${a.name}</small></button>`).join('')}</div>`}
function templatesPanel(){return `<h2 class="panel-title" data-en="Templates" data-fa="قالب‌ها">Templates</h2><div class="search-box"><input placeholder="Search scientific templates…"></div><div class="template-stack"><button class="template-card"><div class="template-preview"><div class="template-sheet"></div></div><div class="template-meta"><b>Mechanism figure</b><span>Publication-ready pathway</span></div></button><button class="template-card"><div class="template-preview"><div class="template-sheet"></div></div><div class="template-meta"><b>Graphical abstract</b><span>Structured manuscript summary</span></div></button><button class="template-card"><div class="template-preview"><div class="template-sheet"></div></div><div class="template-meta"><b>Experimental workflow</b><span>Methods and study design</span></div></button></div>`}
function designPanel(){return `<h2 class="panel-title" data-en="Design tools" data-fa="ابزار طراحی">Design tools</h2><div class="design-stack"><button class="design-action" data-create="text"><b>T</b><span>Text</span></button><button class="design-action" data-create="shape"><b>□</b><span>Shape</span></button><button class="design-action" data-create="arrow"><b>→</b><span>Arrow</span></button><button class="design-action" data-create="label"><b>Aa</b><span>Label</span></button></div>`}
function plotsPanel(){return `<h2 class="panel-title" data-en="Plots & data" data-fa="نمودار و داده">Plots & data</h2><p style="color:var(--muted);font-size:11px;margin-top:-4px">Native scientific plots will live inside the same BioPlot workspace.</p><div class="plot-grid"><button class="plot-card"><div class="plot-preview bars"><i style="height:35%"></i><i style="height:70%"></i><i style="height:50%"></i><i style="height:88%"></i></div><small>Bar plot</small></button><button class="plot-card"><div class="plot-preview scatter"><i style="left:20%;top:62%"></i><i style="left:37%;top:37%"></i><i style="left:56%;top:52%"></i><i style="left:71%;top:24%"></i></div><small>Scatter</small></button><button class="plot-card"><div class="plot-preview bars"><i style="height:80%"></i><i style="height:45%"></i><i style="height:65%"></i><i style="height:32%"></i></div><small>Volcano</small></button><button class="plot-card"><div class="plot-preview scatter"><i style="left:25%;top:28%"></i><i style="left:44%;top:61%"></i><i style="left:60%;top:33%"></i><i style="left:76%;top:68%"></i></div><small>PCA</small></button></div><div style="margin-top:12px;padding:10px;border-radius:9px;background:#f2f7fb;color:#4d6f86;font-size:10px">Coming next: heatmaps, box plots, violin plots, volcano plots, PCA and editable statistical styling.</div>`}
function uploadPanel(){return `<h2 class="panel-title" data-en="Upload" data-fa="آپلود">Upload</h2><div class="upload-drop"><div style="font-size:26px;margin-bottom:7px">⇧</div><b>Upload SVG, PNG or JPG</b><p style="font-size:10px">Your uploaded scientific assets will appear in this project.</p><button class="ghost-btn">Choose files</button></div>`}
function renderPanel(){panelContent.innerHTML=state.panel==='assets'?assetPanel():state.panel==='templates'?templatesPanel():state.panel==='design'?designPanel():state.panel==='plots'?plotsPanel():uploadPanel();bindPanel()}
function bindPanel(){document.querySelectorAll('[data-asset]').forEach(btn=>btn.onclick=()=>addAsset(assets[+btn.dataset.asset]));document.querySelectorAll('[data-create]').forEach(btn=>btn.onclick=()=>createObject(btn.dataset.create));const search=document.getElementById('assetSearch');if(search)search.oninput=()=>{const q=search.value.toLowerCase();document.querySelectorAll('.asset-card').forEach((card,i)=>card.style.display=assets[i].name.toLowerCase().includes(q)||assets[i].cat.toLowerCase().includes(q)?'grid':'none')}}
function saveSnapshot(){state.history.push(artboard.innerHTML);if(state.history.length>25)state.history.shift();state.redo=[]}
function rehydrate(){document.querySelectorAll('.canvas-object').forEach(bindObject);selectObject(document.querySelector('.canvas-object.selected')||document.querySelector('.canvas-object'))}
function bindObject(el){el.onpointerdown=e=>{e.stopPropagation();selectObject(el);saveSnapshot();const sx=e.clientX,sy=e.clientY,left=parseFloat(el.style.left)||0,top=parseFloat(el.style.top)||0;el.setPointerCapture(e.pointerId);el.onpointermove=ev=>{el.style.left=left+(ev.clientX-sx)/state.zoom+'px';el.style.top=top+(ev.clientY-sy)/state.zoom+'px';syncProps()};el.onpointerup=()=>{el.onpointermove=null;el.onpointerup=null;renderLayers();markSaved()}}}
function selectObject(el){document.querySelectorAll('.canvas-object').forEach(o=>o.classList.remove('selected'));state.selected=el;if(el)el.classList.add('selected');syncProps();renderLayers();renderContext()}
function syncProps(){const el=state.selected;if(!el)return;document.getElementById('selectionName').textContent=el.dataset.label||'Object';propX.value=Math.round(parseFloat(el.style.left)||0);propY.value=Math.round(parseFloat(el.style.top)||0);propW.value=Math.round(el.offsetWidth);propH.value=Math.round(el.offsetHeight);const opacity=Math.round((parseFloat(el.style.opacity)||1)*100);opacityRange.value=opacity;opacityValue.textContent=opacity+'%'}
function renderLayers(){layersList.innerHTML=[...document.querySelectorAll('.canvas-object')].reverse().map((o,i)=>`<div class="layer-item ${o===state.selected?'active':''}" data-layer="${i}"><span class="layer-dot"></span><span>${o.dataset.label||'Object'}</span></div>`).join('');const reversed=[...document.querySelectorAll('.canvas-object')].reverse();document.querySelectorAll('[data-layer]').forEach(item=>item.onclick=()=>selectObject(reversed[+item.dataset.layer]))}
function renderContext(){const t=state.selected?.dataset.type;if(!state.selected){contextBar.innerHTML=`<button class="context-tool">↖ Select</button><button class="context-tool" onclick="createObject('text')">T Text</button><button class="context-tool" onclick="createObject('shape')">□ Shape</button><button class="context-tool" onclick="createObject('arrow')">→ Arrow</button>`;return}contextBar.innerHTML=t==='text'?`<button class="context-tool">Inter</button><button class="context-tool"><b>B</b></button><button class="context-tool">Align</button><button class="context-tool" onclick="duplicateSelected()">⧉ Duplicate</button>`:`<button class="context-tool">Color</button><button class="context-tool">Stroke</button><button class="context-tool">Flip</button><button class="context-tool">Rotate</button><button class="context-tool" onclick="duplicateSelected()">⧉ Duplicate</button><button class="context-tool">Arrange</button>`}
function addAsset(asset){saveSnapshot();const el=document.createElement('div');el.className='canvas-object';el.dataset.label=asset.name;el.dataset.type='asset';el.style.cssText='left:390px;top:400px;width:140px;height:100px';el.innerHTML=asset.svg.replace('<svg ','<svg width="100%" height="100%" ');artboard.appendChild(el);bindObject(el);selectObject(el);markSaved()}
function createObject(type){saveSnapshot();const el=document.createElement('div');el.className='canvas-object';el.dataset.type=type;el.style.left='390px';el.style.top='410px';if(type==='text'){el.dataset.label='Scientific text';el.classList.add('text-object');el.style.cssText+=';width:190px;height:42px';el.textContent='Scientific annotation'}else if(type==='shape'){el.dataset.label='Shape';el.style.cssText+=';width:130px;height:82px;background:#dff2ef;border:2px solid #4c9993;border-radius:12px'}else if(type==='arrow'){el.dataset.label='Arrow';el.classList.add('arrow-object');el.style.cssText+=';width:110px;height:44px';el.textContent='→'}else{el.dataset.label='Label';el.classList.add('label-object');el.style.cssText+=';width:110px;height:36px';el.textContent='Label'}artboard.appendChild(el);bindObject(el);selectObject(el);markSaved()}
function duplicateSelected(){if(!state.selected)return;saveSnapshot();const c=state.selected.cloneNode(true);c.classList.remove('selected');c.style.left=(parseFloat(state.selected.style.left)+18)+'px';c.style.top=(parseFloat(state.selected.style.top)+18)+'px';artboard.appendChild(c);bindObject(c);selectObject(c);markSaved()}
function deleteSelected(){if(!state.selected)return;saveSnapshot();state.selected.remove();selectObject(document.querySelector('.canvas-object'));markSaved()}
function undo(){if(!state.history.length)return;state.redo.push(artboard.innerHTML);artboard.innerHTML=state.history.pop();rehydrate();markSaved()}
function redo(){if(!state.redo.length)return;state.history.push(artboard.innerHTML);artboard.innerHTML=state.redo.pop();rehydrate();markSaved()}
function markSaved(){saveState.textContent='Saving…';clearTimeout(window._save);window._save=setTimeout(()=>saveState.textContent='Saved locally',450)}
function setZoom(z){state.zoom=Math.max(.45,Math.min(1.35,z));shell.style.transform=`scale(${state.zoom})`;zoomValue.textContent=Math.round(state.zoom*100)+'%'}
function applyLanguage(){const fa=state.lang==='fa';document.documentElement.lang=fa?'fa':'en';document.documentElement.dir=fa?'rtl':'ltr';document.body.classList.toggle('rtl',fa);langBtn.textContent=fa?'EN':'FA';document.querySelectorAll('[data-en]').forEach(el=>el.textContent=fa?el.dataset.fa:el.dataset.en)}

document.querySelectorAll('.rail-item[data-panel]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.rail-item[data-panel]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.panel=btn.dataset.panel;renderPanel()});
document.querySelectorAll('.canvas-object').forEach(bindObject);
artboard.onpointerdown=e=>{if(e.target===artboard)selectObject(null)};
[propX,propY,propW,propH].forEach(input=>input.onchange=()=>{if(!state.selected)return;saveSnapshot();state.selected.style.left=propX.value+'px';state.selected.style.top=propY.value+'px';state.selected.style.width=Math.max(10,+propW.value)+'px';state.selected.style.height=Math.max(10,+propH.value)+'px';syncProps();markSaved()});
opacityRange.oninput=()=>{if(!state.selected)return;state.selected.style.opacity=opacityRange.value/100;opacityValue.textContent=opacityRange.value+'%';markSaved()};
document.querySelectorAll('.swatch').forEach(btn=>btn.onclick=()=>{if(!state.selected)return;saveSnapshot();const color=btn.dataset.color;if(state.selected.dataset.type==='text'||state.selected.dataset.type==='arrow')state.selected.style.color=color;else state.selected.style.filter=`drop-shadow(0 0 0 ${color})`;markSaved()});
undoBtn.onclick=undo;redoBtn.onclick=redo;deleteBtn.onclick=deleteSelected;zoomIn.onclick=()=>setZoom(state.zoom+.1);zoomOut.onclick=()=>setZoom(state.zoom-.1);fitBtn.onclick=()=>setZoom(.8);gridBtn.onclick=()=>viewport.classList.toggle('grid-on');langBtn.onclick=()=>{state.lang=state.lang==='en'?'fa':'en';applyLanguage()};docTitle.oninput=markSaved;
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicateSelected()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if((e.key==='Delete'||e.key==='Backspace')&&document.activeElement.tagName!=='INPUT')deleteSelected()});

renderPanel();selectObject(document.querySelector('.canvas-object.selected'));setZoom(.8);applyLanguage();
