import {useStudioCopy,StudioBlocks,useStudioContent} from './StudioContent';
import {useState} from 'react';
import {ArrowRight,Flask,Image,PresentationChart,Sparkle,CheckCircle} from '@phosphor-icons/react';
import './orders.css';
export function DesignServices(){
 const [fa,setFa]=useState(()=>localStorage.getItem('bioplot-lang')!=='en');const t=useStudioCopy(fa);const content=useStudioContent();
 return <div className="design-hub" dir={fa?'rtl':'ltr'}><header className="order-nav"><a href="/" className="order-logo">BioPlot<span>STUDIO</span></a><nav><a href="/editor">{t('خودم طراحی می‌کنم','Design it myself')}</a><a href="/orders">{t('سفارش‌های من','My orders')}</a><button onClick={()=>{localStorage.setItem('bioplot-lang',fa?'en':'fa');setFa(!fa);}}>{fa?'EN':'فارسی'}</button></nav></header>
 <main><section className="design-hero"><div><span className="order-eyebrow"><Sparkle size={18}/>{t('همراه شما، از ایده تا تصویر','From an idea to a clear visual')}</span><h1>{t('علم از شما.','Your science.')}<br/><em>{t('روایت تصویری از ما.','Our visual craft.')}</em></h1><p>{t('یک توضیح، طرح اولیه یا نمونه کافی است تا گفت‌وگو را شروع کنیم. تیم BioPlot برای طراحی تصویر علمی، چکیده تصویری و پوستر در کنار شماست.','Start with an explanation, a sketch or a reference. Work with the BioPlot team on scientific illustrations, graphical abstracts and posters.')}</p><div className="order-actions"><a className="order-primary" href="/orders?new=1">{t('درخواست طراحی و برآورد هزینه','Request a design & quote')}<ArrowRight/></a><a href="#how">{t('روند همکاری','How it works')}</a></div><small>{t('قیمت و زمان پس از بررسی درخواست اعلام می‌شود؛ شروع طراحی با تأیید شماست.','Receive a tailored quote and timeline before approving the work.')}</small></div>{content.images.hero?<figure className="studio-hero-image"><img src={content.images.hero} alt={t('تصویر خدمات طراحی','Design services illustration')}/></figure>:<div className="design-story" aria-hidden="true"><div className="story-note">{t('ایدهٔ شما','Your idea')}<svg viewBox="0 0 250 110"><path d="M20 60 Q50 5 85 50 T150 60 M85 50 L130 20 M85 50 L140 100" fill="none" stroke="#95a9a3" strokeWidth="2" strokeDasharray="5 5"/><circle cx="190" cy="55" r="30" fill="none" stroke="#95a9a3" strokeWidth="2"/></svg></div><div className="story-result"><span><CheckCircle/> {t('روایتی روشن و منسجم','A clear visual story')}</span><svg viewBox="0 0 340 180"><defs><linearGradient id="service-cell"><stop stopColor="#b9e8d9"/><stop offset="1" stopColor="#51a795"/></linearGradient></defs><circle cx="75" cy="90" r="48" fill="url(#service-cell)"/><circle cx="75" cy="90" r="23" fill="#147d76"/><path d="M134 90H205m-10-8 10 8-10 8" fill="none" stroke="#2d6e72" strokeWidth="3"/><rect x="228" y="48" width="78" height="84" rx="20" fill="#f3ddac"/><path d="M245 106V85m20 21V68m20 38V78" stroke="#ac7c30" strokeWidth="8" strokeLinecap="round"/></svg></div></div>}</section>
 <section className="design-services"><div className="order-section-heading"><span>{t('چه چیزی می‌سازیم؟','What can we create?')}</span><h2>{t('یک تیم، سه مسیر برای نمایش پژوهش شما','Three ways to tell your research story')}</h2></div><div className="service-grid">{[
 {id:'figure',icon:Flask,title:t('تصویر علمی','Scientific illustration'),text:t('مکانیسم‌ها، مسیرهای زیستی، طرح آزمایش و شکل‌های مقاله.','Mechanisms, biological pathways, study designs and paper figures.')},
 {id:'graphical_abstract',icon:Image,title:t('چکیده تصویری','Graphical abstract'),text:t('تبدیل سؤال، روش و پیام اصلی پژوهش به یک روایت تصویری منسجم.','Bring the question, method and main finding into one cohesive visual.')},
 {id:'poster',icon:PresentationChart,title:t('پوستر علمی','Scientific poster'),text:t('چیدمان خوانا برای ارائه در کنگره، همایش یا جلسه پژوهشی.','A readable layout for conferences, scientific meetings and presentations.')}
 ].map(item=><a className="service-card" href={`/orders?new=1&kind=${item.id}`} key={item.id}>{content.images[item.id]?<img className="studio-service-image" src={content.images[item.id]} alt="" loading="lazy"/>:<item.icon size={32} weight="duotone"/>}<h3>{item.title}</h3><p>{item.text}</p><span>{t('شروع درخواست','Start a request')} <ArrowRight/></span></a>)}</div></section>
 <section id="how" className="design-process"><h2>{t('هر مرحله روشن، هر نسخه در دسترس','Every step visible. Every version accessible.')}</h2><div>{[[t('ایده را بفرستید','Share your idea'),t('توضیح، نمونه یا طرح فعلی را در پرونده سفارش قرار دهید.','Add your brief, references or existing design.')],[t('پیشنهاد را بررسی کنید','Review the quote'),t('مبلغ، خروجی‌ها، زمان و تعداد اصلاحات را پیش از شروع ببینید.','Agree on price, deliverables, timing and revisions.')],[t('روی طرح نظر بدهید','Review the design'),t('پیش‌نمایش را ببینید و اصلاحات را در همان پرونده ثبت کنید.','Check previews and leave revision requests in the same workspace.')],[t('فایل نهایی را بگیرید','Get your final files'),t('نسخه‌های تحویلی را دریافت کنید و تکمیل سفارش را تأیید کنید.','Download the deliverables and confirm completion.')]].map(([title,body],i)=><article key={title}><b>{String(i+1).padStart(2,'0')}</b><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <StudioBlocks page="design" fa={fa}/>
 </main><footer><b>BioPlot</b><span>{t('خودتان بسازید؛ یا با تیم ما بسازید.','Create it yourself, or create it with us.')}</span><a href="/orders?new=1">{t('شروع همکاری','Start a collaboration')}</a></footer></div>;
}
