import {OrderFilePicker} from './OrderFilePicker';
import {useState,type FormEvent} from 'react';
import {DownloadSimple,ChatCircle,Clock,CheckCircle} from '@phosphor-icons/react';
import {allowedTransitions,serviceLabels,statusLabels,type DesignOrder,type OrderFile,type OrderMessage,type OrderEvent,type OrderStatus,type Quote} from './orderModel';
const actionLabels:Partial<Record<OrderStatus,[string,string]>>={reviewing:['شروع بررسی','Start review'],quoted:['ارسال پیشنهاد','Send quote'],accepted:['تأیید پیشنهاد','Accept quote'],designing:['شروع طراحی','Start design'],review:['ارسال برای بازبینی','Send for review'],approved:['تأیید پیش‌نمایش','Approve preview'],revision_requested:['درخواست اصلاح','Request revision'],delivered:['تحویل نهایی','Deliver files'],completed:['تأیید تکمیل سفارش','Confirm completion'],cancelled:['لغو درخواست','Cancel request']};
const fileLabels:Record<OrderFile['kind'],[string,string]>={reference:['نمونه و منابع','References'],preview:['پیش‌نمایش','Previews'],final:['فایل نهایی','Final files']};
export function OrderDetail({fa,admin,userId,order,files,messages,events,busy,onTransition,onMessage,onUpload,onDownload}:{fa:boolean;admin:boolean;userId:string;order:DesignOrder;files:OrderFile[];messages:OrderMessage[];events:OrderEvent[];busy:boolean;onTransition:(status:OrderStatus,note:string,quote?:Quote)=>Promise<boolean>;onMessage:(body:string)=>Promise<boolean>;onUpload:(files:File[],kind:OrderFile['kind'])=>Promise<boolean>;onDownload:(file:OrderFile)=>void}){
 const t=(f:string,e:string)=>fa?f:e;const [action,setAction]=useState<OrderStatus|null>(null),[note,setNote]=useState(''),[message,setMessage]=useState(''),[agree,setAgree]=useState(false),[fileKind,setFileKind]=useState<OrderFile['kind']>('reference');
 const [quote,setQuote]=useState<Quote>({amount:order.quote_amount??0,currency:order.quote_currency??'IRT',scope:order.quote_scope??'',days:order.quote_days??7,revisions:order.quote_revisions??2});
 const terminal=['completed','cancelled'].includes(order.status);const actions=allowedTransitions(order.status,admin);
 const date=(value:string)=>new Date(value).toLocaleString(fa?'fa-IR':'en-US',{dateStyle:'medium',timeStyle:'short'});
 const currency=(value:string|null)=>value==='IRT'?t('تومان','toman'):value==='USD'?t('دلار آمریکا','USD'):t('یورو','EUR');
 const amount=(value:number)=>value.toLocaleString(fa?'fa-IR':'en-US');
 const submitAction=async(e:FormEvent)=>{e.preventDefault();if(action&&await onTransition(action,note,action==='quoted'?quote:undefined)){setAction(null);setNote('');setAgree(false);}};
 const submitMessage=async(e:FormEvent)=>{e.preventDefault();if(await onMessage(message))setMessage('');};
 const stages:OrderStatus[]=['submitted','quoted','designing','review','delivered','completed'];const stageIndex:Record<OrderStatus,number>={submitted:0,reviewing:0,quoted:1,accepted:1,designing:2,review:3,approved:3,revision_requested:3,delivered:4,completed:5,cancelled:-1};
 return <><header className="order-detail-heading"><div><span className="order-eyebrow">{serviceLabels[order.kind][fa?0:1]} · <bdi>#{order.id.slice(0,8)}</bdi></span><h1 dir="auto">{order.title}</h1><small>{t('ثبت‌شده در ','Submitted ')}{date(order.created_at)}</small></div><span className={`order-status status-${order.status}`}>{statusLabels[order.status][fa?0:1]}</span></header>
 {!terminal&&<ol className="order-progress">{stages.map((status,i)=><li key={status} className={i<=stageIndex[order.status]?'reached':''} aria-current={i===stageIndex[order.status]?'step':undefined}><span>{i<stageIndex[order.status]?<CheckCircle/>:i+1}</span>{[t('ثبت درخواست','Request'),t('توافق','Agreement'),t('طراحی','Design'),t('بازبینی','Review'),t('تحویل','Delivery'),t('تکمیل','Complete')][i]}</li>)}</ol>}
 <div className="order-detail-layout"><div className="order-detail-main">
 {order.quote_amount!==null&&<section className="order-card order-quote"><div className="order-section-heading"><span>{t('پیشنهاد تیم','Team proposal')}</span><h2>{amount(order.quote_amount)} <small>{currency(order.quote_currency)}</small></h2></div><div className="quote-facts"><span><Clock/>{order.quote_days} {t('روز پس از تأیید پیشنهاد','days after approval')}</span><span>{order.quote_revisions} {t('نوبت اصلاح در محدوده توافق','revision rounds within scope')}</span></div><p className="order-prewrap">{order.quote_scope}</p><small>{t('تأیید پیشنهاد به معنی پرداخت نیست. شرایط پرداخت و خروجی‌های دقیق باید در متن توافق مشخص باشند. تغییر محدودهٔ کار می‌تواند به پیشنهاد تازه نیاز داشته باشد.','Accepting a quote does not process payment. Payment arrangements and deliverables belong in the agreed scope. Scope changes may require a new quote.')}</small></section>}
 {actions.length>0&&<section className="order-card"><h2>{t('گام بعدی','Next step')}</h2><div className="order-actions">{actions.map(status=><button disabled={busy} className={status==='cancelled'?'order-danger':status==='accepted'?'order-primary':''} key={status} onClick={()=>{setAction(status);setAgree(false);}}>{actionLabels[status]?.[fa?0:1]}</button>)}</div>{action&&actions.includes(action)&&<form className="order-action-form" onSubmit={submitAction}><h3>{actionLabels[action]?.[fa?0:1]}</h3>{action==='revision_requested'&&order.revision_round>=(order.quote_revisions??0)&&<p className="order-hint">{t('تعداد اصلاحات توافق‌شده استفاده شده است. تیم این درخواست را بررسی می‌کند و در صورت نیاز، پیش از شروع پیشنهاد تازه‌ای می‌فرستد.','The agreed revision rounds have been used. The team will review this request and, if needed, send a new quote before proceeding.')}</p>}{action==='quoted'&&<><div className="order-field-grid"><label>{t('مبلغ کل','Total price')}<input required type="number" min="0.01" max="9999999999" step="0.01" value={quote.amount||''} onChange={e=>setQuote({...quote,amount:Number(e.target.value)})}/></label><label>{t('واحد پول','Currency')}<select value={quote.currency} onChange={e=>setQuote({...quote,currency:e.target.value as Quote['currency']})}><option value="IRT">{t('تومان','Toman')}</option><option value="USD">USD</option><option value="EUR">EUR</option></select></label><label>{t('زمان طراحی (روز)','Design time (days)')}<input required type="number" min="1" max="365" value={quote.days} onChange={e=>setQuote({...quote,days:Number(e.target.value)})}/></label><label>{t('تعداد نوبت اصلاح','Included revisions')}<input required type="number" min="0" max="20" value={quote.revisions} onChange={e=>setQuote({...quote,revisions:Number(e.target.value)})}/></label></div><label>{t('محدوده کار، فایل‌های تحویلی و شرایط پرداخت','Scope, deliverables & payment arrangements')}<textarea required minLength={10} maxLength={6000} rows={5} value={quote.scope} onChange={e=>setQuote({...quote,scope:e.target.value})}/></label></>}
 {action==='accepted'?<label className="order-check"><input type="checkbox" required checked={agree} onChange={e=>setAgree(e.target.checked)}/>{t('مبلغ، محدوده کار، زمان و شرایط این پیشنهاد را بررسی و تأیید می‌کنم.','I have reviewed and accept the price, scope, timing and terms of this proposal.')}</label>:<label>{action==='revision_requested'?t('اصلاحات موردنیاز؛ لطفاً نام فایل و بخش مربوط را ذکر کنید','Requested revisions; include the file name and section'):t('توضیح','Note')}<textarea rows={3} required={['revision_requested','cancelled'].includes(action)} minLength={['revision_requested','cancelled'].includes(action)?3:undefined} maxLength={6000} value={note} onChange={e=>setNote(e.target.value)}/></label>}
 <button className="order-primary" disabled={busy}>{t('تأیید و ثبت','Confirm')}</button><button type="button" disabled={busy} onClick={()=>setAction(null)}>{t('انصراف','Back')}</button></form>}</section>}
 <section className="order-card"><div className="order-section-heading"><span><DownloadSimple/>{t('فایل‌های مشترک و نسخه‌های تحویلی','Shared files & deliverables')}</span><h2>{t('همهٔ نسخه‌ها، در یک پرونده','Every version in one place')}</h2></div>{(['final','preview','reference'] as const).map(kind=><div className="order-file-group" key={kind}><h3>{fileLabels[kind][fa?0:1]}</h3>{files.filter(file=>file.kind===kind).length?files.filter(file=>file.kind===kind).map(file=><div className="order-file" key={file.id}><div><b dir="auto">{file.name}</b><small>{date(file.created_at)} · <bdi>{(file.size/1024/1024).toFixed(2)} MB</bdi></small></div><button disabled={busy} onClick={()=>onDownload(file)} aria-label={`${t('دریافت','Download')} ${file.name}`}><DownloadSimple/>{t('دریافت','Download')}</button></div>):<p className="order-muted">{t('هنوز فایلی اضافه نشده است.','No files yet.')}</p>}</div>)}
 {!terminal&&<div className="order-upload">{admin&&<label>{t('نوع فایل اشتراکی','Shared file type')}<select value={fileKind} onChange={e=>setFileKind(e.target.value as OrderFile['kind'])}>{Object.entries(fileLabels).map(([id,labels])=><option key={id} value={id}>{labels[fa?0:1]}</option>)}</select></label>}<OrderFilePicker fa={fa} label={t('افزودن فایل','Add files')} disabled={busy} onChange={e=>{const input=e.currentTarget;const selected=Array.from(input.files||[]);if(selected.length)void onUpload(selected,admin?fileKind:'reference').then(ok=>{if(ok)input.value='';});}}/><small>{t('هر فایل تا ۲۰ مگابایت. فایل‌های بارگذاری‌شده برای هر دو طرف قابل دریافت‌اند و نسخه‌های قبلی حفظ می‌شوند.','Up to 20 MB per file. Uploads are shared with both parties; earlier versions are retained.')}</small></div>}</section>
 <section className="order-card"><h2><ChatCircle/> {t('گفت‌وگوی سفارش','Order conversation')}</h2><div className="order-messages">{messages.length===0?<p className="order-muted">{t('پرسش‌ها و توضیحات تکمیلی را همین‌جا بنویسید.','Keep questions and clarifications here.')}</p>:messages.map(item=><article className={item.author_id===userId?'own':''} key={item.id}><header><b>{item.author_id===order.user_id?t('مشتری','Customer'):t('تیم طراحی','Design team')}</b><small>{date(item.created_at)}</small></header><p className="order-prewrap" dir="auto">{item.body}</p></article>)}</div>{!terminal&&<form onSubmit={submitMessage}><label>{t('پیام جدید','New message')}<textarea required rows={3} maxLength={6000} value={message} onChange={e=>setMessage(e.target.value)}/></label><button className="order-primary" disabled={busy||!message.trim()}>{t('ارسال پیام','Send message')}</button></form>}</section>
 </div><aside className="order-detail-side"><section className="order-card"><h2>{t('شرح سفارش','Order brief')}</h2><dl><dt>{t('روش شروع','Starting point')}</dt><dd>{order.brief.route==='idea'?t('طراحی از ایده','From an idea'):order.brief.route==='reference'?t('بر اساس نمونه','From references'):t('تکمیل طرح','Refine a draft')}</dd><dt>{t('پیام علمی','Scientific message')}</dt><dd className="order-prewrap" dir="auto">{order.brief.message}</dd>{[[t('مخاطب','Audience'),order.brief.audience],[t('الزامات','Requirements'),order.brief.requirements],[t('سبک','Style'),order.brief.style],[t('موعد درخواستی (تأییدنشده)','Requested date (unconfirmed)'),order.requested_date],[t('خروجی‌های درخواستی','Requested formats'),order.brief.formats.join(' · ')]].map(([label,value])=>value?<div key={label}><dt>{label}</dt><dd dir="auto">{value}</dd></div>:null)}</dl></section><section className="order-card"><h2>{t('تاریخچه سفارش','Order history')}</h2><ol className="order-timeline">{events.slice().reverse().map(event=><li key={event.id}><b>{statusLabels[event.status]?.[fa?0:1]}</b><small>{date(event.created_at)}</small>{typeof event.detail.note==='string'&&event.detail.note&&<p dir="auto">{event.detail.note}</p>}{typeof event.detail.scope==='string'&&<details><summary>{t('متن توافق در این مرحله','Agreement at this step')}</summary><p className="order-prewrap" dir="auto">{event.detail.scope}</p><small>{amount(Number(event.detail.amount))} {currency(String(event.detail.currency))} · {String(event.detail.days)} {t('روز','days')} · {String(event.detail.revisions)} {t('اصلاح','revisions')}</small></details>}</li>)}</ol></section></aside></div></>;
}
