import {OrderFilePicker} from './OrderFilePicker';
import {readOrderSource} from './orderSource';
import {useState,type FormEvent} from 'react';
import {serviceLabels,validBrief,validateOrderFile,type OrderBrief,type ServiceKind} from './orderModel';
export function OrderForm({fa,userId,onSubmit,busy,onCancel}:{fa:boolean;userId:string;onSubmit:(input:{id:string;title:string;kind:ServiceKind;brief:OrderBrief;requested_date:string|null},files:File[])=>Promise<void>;busy:boolean;onCancel:()=>void}){
 const t=(f:string,e:string)=>fa?f:e;const key=`bioplot-order-draft:${userId}`;const [source]=useState(readOrderSource);
 const [draft,setDraft]=useState(()=>{try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');if(saved?.brief&&typeof saved.id==='string'&&typeof saved.title==='string'&&saved.kind in serviceLabels&&Array.isArray(saved.brief.formats)&&typeof saved.brief.message==='string')return saved as {id:string;title:string;kind:ServiceKind;brief:OrderBrief;requested_date:string};}catch{/* Invalid local draft is discarded. */}const kind=new URLSearchParams(location.search).get('kind');return {id:crypto.randomUUID(),title:source?.title==='Untitled scientific figure'?'':source?.title||'',kind:(kind&&kind in serviceLabels?kind:'figure') as ServiceKind,brief:{route:source?'polish':'idea',sourceProject:source?.projectId,message:'',audience:'',requirements:'',style:'',formats:['PNG','SVG']} as OrderBrief,requested_date:''};});
 const [step,setStep]=useState(0),[files,setFiles]=useState<File[]>(()=>source?[new File([source.svg],'bioplot-draft.svg',{type:'image/svg+xml'})]:[]),[error,setError]=useState('');
 const update=(patch:Partial<typeof draft>)=>{setDraft(current=>{const next={...current,...patch};try{sessionStorage.setItem(key,JSON.stringify(next));}catch{/* Draft storage is optional. */}return next;});};
 const brief=(patch:Partial<OrderBrief>)=>update({brief:{...draft.brief,...patch}});
 const submit=(event:FormEvent)=>{event.preventDefault();if(!validBrief(draft.title,draft.brief)){setError(t('عنوان، توضیح علمی (حداقل ۲۰ نویسه) و خروجی‌های موردنیاز را تکمیل کنید.','Add a title, a brief of at least 20 characters, and requested formats.'));return;}void onSubmit({...draft,requested_date:draft.requested_date||null},files);};
 return <form className="order-form order-card" onSubmit={submit}><div className="order-section-heading"><span>{t('سفارش جدید','New request')}</span><h2>{t('از ایدهٔ شما شروع کنیم','Let’s start with your idea')}</h2></div><ol className="order-form-steps">{[t('نوع همکاری','Starting point'),t('شرح علمی','Scientific brief'),t('نمونه و بازبینی','References & review')].map((label,i)=><li key={label} aria-current={step===i?'step':undefined}><button type="button" onClick={()=>setStep(i)} disabled={busy}><b>{i+1}</b>{label}</button></li>)}</ol>
 {step===0&&<><label>{t('نوع سفارش','Service')}<select value={draft.kind} onChange={e=>update({kind:e.target.value as ServiceKind})}>{Object.entries(serviceLabels).map(([id,label])=><option value={id} key={id}>{label[fa?0:1]}</option>)}</select></label><fieldset><legend>{t('از کجا شروع کنیم؟','What is your starting point?')}</legend><div className="order-choice-grid">{(['idea','reference','polish'] as const).map((route,i)=><label className={draft.brief.route===route?'selected':''} key={route}><input type="radio" name="route" value={route} checked={draft.brief.route===route} onChange={()=>brief({route})}/><b>{[t('یک ایده دارم','I have an idea'),t('نمونه دارم','I have a reference'),t('طرحی برای تکمیل دارم','I have a draft')][i]}</b><span>{[t('پیام و هدف را توضیح می‌دهم.','I will explain the message.'),t('نمونه یا قالب را می‌فرستم.','I will share a reference.'),t('طرح فعلی را برای بازطراحی می‌فرستم.','I will share my current design.')][i]}</span></label>)}</div></fieldset><label>{t('عنوان سفارش','Order title')}<input value={draft.title} maxLength={160} onChange={e=>update({title:e.target.value})} placeholder={t('مثلاً: مکانیسم اثر دارو بر سلول توموری','e.g. Drug mechanism in tumor cells')}/></label></>}
 {step===1&&<><label>{t('پیام اصلی و اجزای علمی تصویر','Main message and scientific elements')}<textarea rows={6} value={draft.brief.message} maxLength={12000} onChange={e=>brief({message:e.target.value})} placeholder={t('مخاطب باید چه چیزی بفهمد؟ چه سلول‌ها، مولکول‌ها، مراحل یا ارتباط‌هایی باید دیده شوند؟ جهت پیکان‌ها و نتیجه نهایی را هم توضیح دهید.','What should the reader understand? Describe the cells, molecules, steps, relationships, arrow directions and key finding.')}/></label><div className="order-field-grid"><label>{t('کاربرد و مخاطب','Audience & use')}<input maxLength={500} value={draft.brief.audience} onChange={e=>brief({audience:e.target.value})} placeholder={t('مقاله، کنفرانس، پایان‌نامه…','Paper, conference, thesis…')}/></label><label>{t('تاریخ موردنیاز شما (اختیاری)','Requested date (optional)')}<input type="date" min={new Date().toISOString().slice(0,10)} value={draft.requested_date} onChange={e=>update({requested_date:e.target.value})}/></label></div><label>{t('الزامات خروجی','Output requirements')}<textarea rows={2} maxLength={3000} value={draft.brief.requirements} onChange={e=>brief({requirements:e.target.value})} placeholder={t('نام مجله، اندازه، زبان نوشته‌ها، تعداد پنل‌ها و دستورالعمل‌ها','Journal, dimensions, text language, number of panels and guidelines')}/></label><label>{t('سبک و رنگ دلخواه','Style & colors')}<input maxLength={1000} value={draft.brief.style} onChange={e=>brief({style:e.target.value})} placeholder={t('ساده و مینیمال، رنگ‌های مشخص، مشابه نمونه…','Minimal, specific colors, similar to a reference…')}/></label><fieldset><legend>{t('فایل‌های موردنیاز','Requested formats')}</legend><div className="order-format-choices">{['PNG','PDF','SVG','PPTX'].map(format=><label key={format}><input type="checkbox" checked={draft.brief.formats.includes(format)} onChange={e=>brief({formats:e.target.checked?[...draft.brief.formats,format]:draft.brief.formats.filter(f=>f!==format)})}/><bdi>{format}</bdi></label>)}</div><small>{t('فرمت قابل‌ویرایش و جزئیات تحویل در پیشنهاد تیم نهایی می‌شود.','Editable formats and deliverables are finalized in the quote.')}</small></fieldset></>}
 {step===2&&<><div className="order-upload"><OrderFilePicker fa={fa} label={t('نمونه، قالب، مقاله یا طرح اولیه (اختیاری)','References, templates or a draft (optional)')} onChange={e=>{const selected=Array.from(e.target.files||[]);if(selected.length+files.length>8||selected.some(file=>!validateOrderFile(file))){setError(t('حداکثر ۸ فایل؛ هر فایل تا ۲۰ مگابایت با قالب مجاز.','Up to 8 supported files, 20 MB each.'));return;}setFiles(current=>[...current,...selected].slice(0,8));setError('');}}/><small><bdi>PDF · PNG · JPG · WebP · SVG · PPTX · DOCX · ZIP</bdi></small><span>{t('فایل‌ها فقط در دسترس شما و مدیران تیم قرار می‌گیرند.','Files are accessible only to you and team administrators.')}</span></div>{source&&files.some(file=>file.name==='bioplot-draft.svg')&&<p className="order-hint">{t('یک نسخه از بوم به نام bioplot-draft.svg به درخواست پیوست شده است. با ثبت سفارش برای تیم ارسال می‌شود.','A canvas snapshot is attached as bioplot-draft.svg. It will be sent to the team when you submit.')}</p>}{files.map((file,i)=><div className="order-picked-file" key={`${file.name}-${i}`}><bdi>{file.name}</bdi><button type="button" onClick={()=>setFiles(current=>current.filter((_,index)=>index!==i))}>{t('حذف','Remove')}</button></div>)}<div className="order-brief-summary"><h3>{t('خلاصه درخواست','Request summary')}</h3><b>{draft.title||t('عنوان هنوز وارد نشده','Title not entered')}</b><p>{serviceLabels[draft.kind][fa?0:1]}</p><p>{draft.brief.message||t('توضیح علمی هنوز وارد نشده','Brief not entered')}</p><small>{t('خروجی‌های درخواستی: ','Requested formats: ')}<bdi>{draft.brief.formats.join(' · ')}</bdi></small></div><p className="order-hint">{t('این مرحله فقط ثبت درخواست است و پرداختی انجام نمی‌شود. موعد درخواستی شما پس از بررسی تیم تأیید خواهد شد. فایل‌های نمونه را تنها در صورتی ارسال کنید که اجازه استفاده از آن‌ها را دارید.','This submits a request without taking payment. The team will confirm timing. Only share reference materials you have permission to use.')}</p></>}
 {error&&<p role="alert" className="order-alert">{error}</p>}<div className="order-actions"><button type="button" onClick={step?()=>setStep(step-1):onCancel} disabled={busy}>{step?t('مرحله قبل','Back'):t('بازگشت','Cancel')}</button>{step<2?<button key="next-step" className="order-primary" type="button" onClick={event=>{event.preventDefault();setStep(step+1);}}>{t('ادامه','Continue')}</button>:<button key="submit-order" type="submit" className="order-primary" disabled={busy}>{busy?t('در حال ثبت…','Submitting…'):t('ثبت درخواست و دریافت برآورد','Submit request for a quote')}</button>}</div></form>;
}
