import { assetToObject, searchAssets } from './assets';
import { ArrowObject, BioPlotObject, makeId, TextObject } from './model';

export interface DraftRequest {
  prompt: string;
  locale: 'en' | 'fa';
}

export interface DraftResponse {
  objects: BioPlotObject[];
  note: string;
}

export interface BioPlotAIProvider {
  draft(request: DraftRequest): Promise<DraftResponse>;
}

const text = (value: string, x: number, y: number, width = 220): TextObject => ({
  id: makeId(),
  type: 'text',
  name: value.slice(0, 32),
  text: value,
  x,
  y,
  width,
  height: 38,
  rotation: 0,
  opacity: 1,
  color: '#17303f',
  fontSize: 16,
  fontWeight: 700,
  align: 'center'
});

const arrow = (x: number, y: number, width = 90): ArrowObject => ({
  id: makeId(),
  type: 'arrow',
  name: 'AI arrow',
  x,
  y,
  width,
  height: 26,
  rotation: 0,
  opacity: 1,
  stroke: '#607986',
  strokeWidth: 3,
  arrowHead: 'end'
});

export class LocalDraftProvider implements BioPlotAIProvider {
  async draft(request: DraftRequest): Promise<DraftResponse> {
    const q = request.prompt.toLowerCase();
    const terms = ['neuron', 'mitochond', 'dna', 'cell', 'نورون', 'میتوکندری', 'سلول'];
    const matched = terms
      .filter(term => q.includes(term))
      .flatMap(term => searchAssets(term, request.locale))
      .filter((asset, index, list) => list.findIndex(item => item.id === asset.id) === index)
      .slice(0, 3);

    const assets = matched.length ? matched : searchAssets('cell', request.locale).slice(0, 1);
    const objects: BioPlotObject[] = [];
    objects.push(text(request.prompt.length > 55 ? `${request.prompt.slice(0, 52)}…` : request.prompt, 250, 115, 460));
    assets.forEach((asset, index) => {
      objects.push(assetToObject(asset, 180 + index * 260, 260));
      if (index < assets.length - 1) objects.push(arrow(330 + index * 260, 300));
    });
    return {
      objects,
      note: request.locale === 'fa' ? 'پیش‌نویس قابل ویرایش با موتور محلی BioPlot ساخته شد.' : 'Editable first draft generated by the local BioPlot drafting engine.'
    };
  }
}

export class RemoteDraftProvider implements BioPlotAIProvider {
  constructor(private endpoint: string) {}
  async draft(request: DraftRequest): Promise<DraftResponse> {
    const response = await fetch(this.endpoint, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(request)
    });
    if (!response.ok) throw new Error(`AI draft request failed (${response.status}).`);
    return response.json() as Promise<DraftResponse>;
  }
}

export function createAIProvider(): BioPlotAIProvider {
  const endpoint = import.meta.env.VITE_BIOPLOT_AI_ENDPOINT as string | undefined;
  return endpoint ? new RemoteDraftProvider(endpoint) : new LocalDraftProvider();
}
