import type { CSSProperties } from 'react';
import { AlignBottomSimple, AlignCenterHorizontal, AlignCenterHorizontalSimple, AlignCenterVertical, AlignCenterVerticalSimple, AlignLeftSimple, AlignRightSimple, AlignTopSimple, ArrowElbowDownRight, ArrowRight, ArrowUUpLeft, ArrowUUpRight, BezierCurve, CaretRight, Check, Circle, CirclesThreePlus, Clock, Copy, CopySimple, CornersOut, DotsThreeVertical, DownloadSimple, EyeSlash, Flask, FolderSimple, FrameCorners, Graph, GridNine, House, ImageSquare, LockSimple, LockSimpleOpen, MagnifyingGlass, Minus, PaintBucket, Pause, Play, PencilSimple, Pill, Plus, Rectangle, SelectionAll, SelectionBackground, SelectionForeground, SelectionSlash, Shapes, ShareNetwork, ShieldCheck, SidebarSimple, SlidersHorizontal, Sparkle, SquaresFour, Stack, Star, TextT, Trash, UploadSimple, X } from '@phosphor-icons/react';

// One optical family for every Home and Figure Studio control.
const icons = {
  play: Play,
  pause: Pause,
  plus: Plus,
  minus: Minus,
  fit: CornersOut,
  grid: GridNine,
  canvas: FrameCorners,
  paint: PaintBucket,
  chevron: CaretRight,
  assets: SquaresFour,
  elements: Shapes,
  upload: UploadSimple,
  download: DownloadSimple,
  copy: Copy,
  duplicate: CopySimple,
  front: SelectionForeground,
  back: SelectionBackground,
  group: SelectionAll,
  ungroup: SelectionSlash,
  lock: LockSimple,
  unlock: LockSimpleOpen,
  hide: EyeSlash,
  trash: Trash,
  left: AlignLeftSimple,
  center: AlignCenterHorizontalSimple,
  right: AlignRightSimple,
  top: AlignTopSimple,
  middle: AlignCenterVerticalSimple,
  bottom: AlignBottomSimple,
  horizontal: AlignCenterHorizontal,
  vertical: AlignCenterVertical,
  settings: SlidersHorizontal,
  layers: Stack,
  check: ShieldCheck,
  close: X,
  search: MagnifyingGlass,
  star: Star,
  clock: Clock,
  undo: ArrowUUpLeft,
  redo: ArrowUUpRight,
  share: ShareNetwork,
  arrow: ArrowRight,
  panel: SidebarSimple,
  text: TextT,
  rect: Rectangle,
  ellipse: Circle,
  connector: ArrowElbowDownRight,
  curve: BezierCurve,
  image: ImageSquare,
  home: House,
  projects: FolderSimple,
  templates: SquaresFour,
  figure: Graph,
  graph: Graph,
  dots: DotsThreeVertical,
  edit: PencilSimple,
  sparkle: Sparkle,
  done: Check,
  folder: FolderSimple,
  flask: Flask,
  pill: Pill,
  cell: CirclesThreePlus,
} as const;
export type StudioIconName = keyof typeof icons;
export function StudioIcon({name, style, size=20, weight='regular'}:{name:StudioIconName;style?:CSSProperties;size?:number;weight?:'regular'|'duotone'}) {
  const Glyph = icons[name];
  return <Glyph className="studio-ui-icon" size={size} weight={weight} aria-hidden="true" focusable="false" style={style}/>;
}
