create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  preferred_language text not null default 'en' check (preferred_language in ('en','fa')),
  plan text not null default 'free' check (plan in ('free','pro','team','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Untitled project',
  project_type text not null default 'figure' check (project_type in ('figure','plot','graphical_abstract','pathway','network','poster','presentation')),
  content jsonb not null default '{}'::jsonb,
  thumbnail_path text,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index projects_owner_updated_idx on public.projects(owner_id, updated_at desc);
create index projects_owner_type_idx on public.projects(owner_id, project_type);

create table public.project_versions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  version_number bigint generated by default as identity,
  content jsonb not null,
  created_at timestamptz not null default now()
);
create index project_versions_project_created_idx on public.project_versions(project_id, created_at desc);
create index project_versions_owner_idx on public.project_versions(owner_id);

create table public.assets (
  id uuid primary key default gen_random_uuid(), name text not null, category text not null, subcategory text,
  keywords text[] not null default '{}', keywords_fa text[] not null default '{}',
  asset_type text not null default 'svg' check (asset_type in ('svg','png','jpg')),
  storage_path text not null unique, thumbnail_path text, is_premium boolean not null default false,
  is_reviewed boolean not null default false, is_published boolean not null default false,
  metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index assets_category_idx on public.assets(category, subcategory);
create index assets_published_idx on public.assets(is_published, is_premium);
create index assets_keywords_gin_idx on public.assets using gin(keywords);
create index assets_keywords_fa_gin_idx on public.assets using gin(keywords_fa);

create table public.templates (
  id uuid primary key default gen_random_uuid(), name text not null,
  template_type text not null default 'figure' check (template_type in ('figure','plot','graphical_abstract','pathway','network','poster','presentation')),
  content jsonb not null default '{}'::jsonb, thumbnail_path text, tags text[] not null default '{}',
  is_premium boolean not null default false, is_published boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index templates_type_idx on public.templates(template_type, is_published);
create index templates_tags_gin_idx on public.templates using gin(tags);

create or replace function public.set_updated_at() returns trigger language plpgsql security invoker set search_path = '' as $$
begin new.updated_at = now(); return new; end; $$;
create trigger set_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger set_projects_updated_at before update on public.projects for each row execute function public.set_updated_at();
create trigger set_assets_updated_at before update on public.assets for each row execute function public.set_updated_at();
create trigger set_templates_updated_at before update on public.templates for each row execute function public.set_updated_at();

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)));
  return new;
end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
revoke execute on function public.handle_new_user() from public, anon, authenticated;

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.project_versions enable row level security;
alter table public.assets enable row level security;
alter table public.templates enable row level security;

create policy "profiles_select_own" on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy "profiles_update_own" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy "projects_select_own" on public.projects for select to authenticated using ((select auth.uid()) = owner_id);
create policy "projects_insert_own" on public.projects for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy "projects_update_own" on public.projects for update to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy "projects_delete_own" on public.projects for delete to authenticated using ((select auth.uid()) = owner_id);
create policy "project_versions_select_own" on public.project_versions for select to authenticated using ((select auth.uid()) = owner_id);
create policy "project_versions_insert_own" on public.project_versions for insert to authenticated with check ((select auth.uid()) = owner_id and exists (select 1 from public.projects p where p.id = project_id and p.owner_id = (select auth.uid())));
create policy "project_versions_delete_own" on public.project_versions for delete to authenticated using ((select auth.uid()) = owner_id);
create policy "assets_read_published" on public.assets for select to anon, authenticated using (is_published = true);
create policy "templates_read_published" on public.templates for select to anon, authenticated using (is_published = true);
